import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import MidBanner from "../general_components/banners/MidBanner";
import SiteHeader from "../general_components/navs/SiteHeader";
import RightBanner from "../general_components/banners/RightBanner";
import Footer from "../general_components/navs/footers/Footer";

export const metadata: Metadata = {
  title: "GlassInformer",
  description: "Generated by GlassInformer",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col">
      <SiteHeader />
      <div className="flex min-h-screen flex-row bg-white pt-4 text-gray-600">
        <div className="w-full lg:w-[80%] flex-shrink-0 px-12 mt-8 lg:mt-0">
          <div className="flex flex-col">
            {/* Navegación - oculta en móvil/tablet, visible en PC (≥1024px) */}
            <div className="mb-4 hidden flex-row bg-blue-950 text-sm font-sans uppercase tracking-wider text-white lg:flex">
              <Link href="/" className="flex-1 cursor-pointer bg-transparent p-2 text-center text-sm hover:bg-blue-900">
                Home
              </Link>
              <Link href="/publications" className="flex-1 cursor-pointer bg-transparent p-2 text-center text-sm hover:bg-blue-900">
                Publications
              </Link>
              <Link href="/directory" className="flex-1 cursor-pointer bg-transparent p-2 text-center text-sm hover:bg-blue-900">
                Directory
              </Link>
              <Link href="/events" className="flex-1 cursor-pointer bg-transparent p-2 text-center text-sm hover:bg-blue-900">
                Events
              </Link>
            </div>
            {children}
            <MidBanner />
            <Footer />
          </div>
        </div>
        {/* Sidebar de banners - visible solo en PC (≥1024px), oculto en móvil/tablet */}
        <div className="hidden lg:block w-[20%] flex-shrink-0 pl-6 bg-white">
          <RightBanner />
        </div>
      </div>
    </div>
  );
}
