import type { Metadata } from "next";
import "../globals.css";
import MainLayoutClient from "./_components/MainLayoutClient";

export const metadata: Metadata = {
  title: "GlassInformer",
  description: "Generated by GlassInformer",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <MainLayoutClient>{children}</MainLayoutClient>;
}
