import type { Metadata } from "next";
import "../globals.css";
import TopBanner from "../general_components/banners/TopBanner";
import RightBanner from "../general_components/banners/RightBanner";
import Link from "next/link";
import AppNav from "../general_components/navs/AppNav";
import Footer from "../general_components/navs/footers/Footer";

export const metadata: Metadata = {
  title: "GlassInformer",
  description: "Generated by GlassInformer",
};

export default function LoggedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col">
      <div className="fixed top-0 left-0 right-0 z-50">
        <div className="bg-gray-100 w-full">
          <TopBanner />
        </div>
        <AppNav />
      </div>
      <div className="flex flex-row bg-gray-100 min-h-screen text-gray-600 pt-48">
        {/* Contenedor principal - 7/10 en desktop/tablet, 100% en móvil */}
        <div className="w-full md:w-[80%] flex-shrink-0 px-12 mt-8">
          <div className="flex flex-col">
            {/* Navegación */}
            <div className='flex flex-row text-sm text-gray-500 uppercase tracking-wider font-sans text-white bg-white mb-4'>
              <Link href='/logged/' className='flex-1 bg-blue-950 hover:bg-blue-950/80 cursor-pointer p-2 text-sm text-center'>
                Home
              </Link>
              <Link href='/publications' className='flex-1 bg-blue-950 hover:bg-blue-950/80 cursor-pointer p-2 text-sm text-center'>
                Publications
              </Link>
              <Link href='/directory' className='flex-1 bg-blue-950 hover:bg-blue-950/80 cursor-pointer p-2 text-sm text-center'>
                Directory
              </Link>
              <Link href='/events' className='flex-1 bg-blue-950 hover:bg-blue-950/80 cursor-pointer p-2 text-sm text-center'>
                Events
              </Link>
            </div>
            <div className="pt-12">
            {children}
            </div>
            <Footer />
          </div>
        </div>
        {/* Sidebar de banners - 3/10 en desktop/tablet, oculto en móvil */}
        <div className="hidden md:block w-[20%] flex-shrink-0 pl-6 bg-white">
          <RightBanner />
        </div>
      </div>
    </div>
  );
}
